name: GitHub Actions Demo 
run-name: ${{github.actor}} is testing out GitHub Actions

on: [push]
jobs: 
  Explore-GitHub-Actions:
    runs-on: ubuntu.latest
    steps: 
    - run: echo "the job was automatic triggered by a ${{ github.event_name }} evente."
    - run: echo " this job is now runnig on a ${{ runner.os }} server hosted by GitHub!"
    - run: echo " the name of your branch is ${{ github.ref }} and your repository is ${{github.repository}}"
    - name: check out repository code 
      uses: actions/checkout@v4
    - run: echo " the ${{github.repository}} repositoryhas been cloned to the runner."
    - run: echo " the worflow is now ready to test your code ont the runner."
    - name: list files in the repository
      run: |
        is ${{github.workspace}}
        - run: echo " this job's status is ${{job.status}}"  
