name: Run Hello Python  

on:
  push:
    branches: [ "main" ]  
  workflow_dispatch:      

jobs:
  run-python-script:
    name: Execute Python Script
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  
      - name: Run Python Script
        run: python hello.py  
