name: CI - Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore ./petcore/ExploringActions/ExploringActions.sln

      - name: Build solution
        run: dotnet build ./petcore/ExploringActions/ExploringActions.sln --configuration Release --no-restore

      - name: Run unit tests
        run: dotnet test ./petcore/ExploringActions/TestExploringActions/TestExploringActions.csproj --configuration Release --no-build --logger "trx;LogFileName=TestResults.trx"

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: UnitTestResults
          path: ./petcore/ExploringActions/TestExploringActions/TestResults/TestResults.trx
