name: Pruebas Unitarias .NET Core

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ejecutar-pruebas:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar código del repositorio
      uses: actions/checkout@v4

    - name: Configurar .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'

    - name: Restaurar dependencias
      run: dotnet restore ./anuncios/

    - name: Compilar proyecto
      run: dotnet build ./anuncios/ --configuration Release --no-restore

    - name: Ejecutar pruebas unitarias
      run: dotnet test ./anuncios/ --configuration Release --no-build --logger "trx;LogFileName=ResultadosPruebas.trx"

    - name: Subir resultados de pruebas
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: resultados-pruebas-unitarias
        path: ./anuncios/**/TestResults/ResultadosPruebas.trx
